version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:90:5e:75:b6:2c:3c:a3:46:51:4a:09:ac:d9:84:0f"
      - run: apt-get install make git
      - run: apt-get install jags
      - run: apt-get install -y gsl-bin libgsl-dev
      - run: apt-get install libudunits2-0
      - checkout
      - run:
           name: installing packages
           command: |
               Rscript setup/package_installs.R
      - run:
           name: rendering pdf
           command: |
             make render-pdf
      - run:
           name: rendering epub
           command: |
             make render-epub
      - run:
           name: rendering gitbook
           command: |
             make render-gitbook
