version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse
    steps:
      - run: apt-get install make
      - checkout
      - run: conda install -c r r
      - run:
           name: rendering gitbook
           command: |
             make render-gitbook
